# Generated by Django 6.0.1 on 2026-07-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=2)),
                ('resumo_profissional', models.TextField()),
                ('criado_em', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoTemFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.candidato')),
                ('id_funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.candidato')),
            ],
        ),
    ]
