# Generated by Django 6.0.1 on 2026-07-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatotemfuncao',
            old_name='id_candidato',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='candidatotemfuncao',
            old_name='id_funcao',
            new_name='funcao',
        ),
        migrations.RenameField(
            model_name='telefonecandidato',
            old_name='id_candidato',
            new_name='candidato',
        ),
    ]
