# Generated by Django 6.0.1 on 2026-07-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=15)),
                ('criado_em', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=2)),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField()),
                ('processo_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recrutador.processoseletivo')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoInscritoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField()),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.candidato')),
                ('id_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutador.processoseletivo')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoTemFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.funcao')),
                ('id_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutador.processoseletivo')),
            ],
        ),
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField()),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recrutador.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='id_recrutador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recrutador.recrutador'),
        ),
    ]
