# Generated by Django 6.0.1 on 2026-07-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatoinscritoprocesso',
            old_name='id_candidato',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='candidatoinscritoprocesso',
            old_name='id_processo',
            new_name='processo',
        ),
        migrations.RenameField(
            model_name='processoseletivo',
            old_name='id_recrutador',
            new_name='recrutador',
        ),
        migrations.RenameField(
            model_name='processotemfuncao',
            old_name='id_funcao',
            new_name='funcao',
        ),
        migrations.RenameField(
            model_name='processotemfuncao',
            old_name='id_processo',
            new_name='processo',
        ),
        migrations.RenameField(
            model_name='recrutador',
            old_name='id_empresa',
            new_name='empresa',
        ),
    ]
